# Generated by Django 5.1.7 on 2025-03-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospokemon',
            name='nombreInvertido',
            field=models.CharField(blank=True, max_length=100, verbose_name='NombreInvertido'),
        ),
    ]
